### ISSUE TITLE
how to run it ?

### ISSUE THREAD

**Issue by andrewpedia** [RohitEdathil/ConsoleBars#2]

**Comment by RohitEdathil** [comment]
Like shown in the example, create an instance of FillingBar object
```dart
final p = FillingBar(desc: "Loading", total: 1000, time: true, percentage:true);
```
This automatically renders the initial state of the progress bar


Calling, increment() method on the instance will increase the value by one and renders the frame.
```dart
p.increment();
```

Calling, update(n) method on the instance will set the value to n and renders the frame.
```dart
p.update(10);
```

**Comment by RohitEdathil** [comment]
@andrewpedia Close the issue if it worked for you or else if you are seeing an error or any unexpected behaviour please say so.

**Comment by RohitEdathil** [comment]
Closing the issue as there was no more follow ups
