### ISSUE TITLE
time: true makes the whole thing just stop

### ISSUE THREAD

**Issue by TheLastGimbus** [RohitEdathil/ConsoleBars#4]
Hi there!
I tried using your bar. Very nice!

However, if i set `time: true`, my code doesn't execute at all :/ all i see is the time being nicely updated

Maybe you wanted to update it per-second, messed something with streams, and that's why. How about, the time updating only when you call `.increment()` :eyes: ?

Cheers

**Comment by RohitEdathil** [comment]
Can I see your code? 
Also, did you use this with flutter?

**Comment by TheLastGimbus** [comment]
My whole code is here: https://github.com/TheLastGimbus/GooglePhotosTakeoutHelper/tree/gpth_dart (gpth_dart branch)

And here is the part where `time: true` breaks stuff:

https://github.com/TheLastGimbus/GooglePhotosTakeoutHelper/blob/3a09f79c74213706c8ca8a7934bd8baef3d072ea/bin/gpth.dart#L274-L288

**Comment by RohitEdathil** [comment]
Hey @TheLastGimbus ,

Can you please upgrade to 1.1.0 which I just published? The issue has been identified and fixed.

Past me thought using `sleep()` inside the auto-rendering loop was a good idea 😅 (it was clearly not). 

When the class is used within an asynchronous context (which I haven't tested before)  `sleep()`  which was used internally inside a loop to periodically update the bar was blocking the thread. Now I have swapped out `sleep()` with `Future.delayed()` which will not block the thread.

Also, I have updated the example, which now uses the class with ` time: true` within an asynchronous context and it is working fine.

### I believe you could now just upgrade the version, set `time: true` and the thing will be up and running 

Please do let me know if this fixes the issue for you.

Thanks for bringing this issue into my notice 🍻

**Comment by TheLastGimbus** [comment]
Very cool, i comfirm it works now :tada: thanks!
